# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v9.0.3.2
_src_path: gh:zamberjo/doodba-copier-template
backup_deletion: true
backup_dst: /var/backup
backup_email_from: zamberjo@gmail.com
backup_email_to: zamberjo@gmail.com
backup_image_version: latest
backup_tz: Europe/Madrid
cidr_whitelist: null
domains_prod:
  - hosts:
      - capili.lapanacea.es
domains_test:
  - hosts:
      - testcapili.lapanacea.es
gitlab_url: https://github.com/zamberjo/capili-doodba-project
odoo_dbfilter: ^capili
odoo_initial_lang: es_ES
odoo_listdb: false
odoo_listdb_staging: false
odoo_oci_image: ghcr.io/zamberjo/capili-odoo
odoo_proxy: traefik
odoo_version: 18.0
paths_with_crawlers:
  - /web/image/website
paths_without_crawlers:
  - /web
  - /website/info
postgres_dbname: capili
postgres_exposed: false
postgres_username: odoo
postgres_version: "17"
project_author: Jose Zambudio Bernabeu
project_license: no_license
project_name: capili
smtp_default_from: zamberjo@gmail.com
smtp_relay_host: ""
traefik_version: 2
