version: "2.4"

services:
  odoo:
    extends:
      file: common.yaml
      service: odoo
    restart: unless-stopped
    hostname: "capili.lapanacea.es"
    env_file:
      - .docker/odoo.env
      - .docker/db-access.env
    environment:
      DB_FILTER: "^capili"
      DOODBA_ENVIRONMENT: "${DOODBA_ENVIRONMENT-prod}"
      INITIAL_LANG: "es_ES"
      PGHOST: capili-14-0-prod-db
    depends_on:
      - db
    networks:
      default:
      inverseproxy_shared:
    labels:
      doodba.domain.main: "capili.lapanacea.es"
      traefik.enable: "true"
      traefik.domain: "capili.lapanacea.es"
      traefik.forbiddenCrawlers-0.frontend.headers.customResponseHeaders:
        "X-Robots-Tag:noindex, nofollow"
      traefik.forbiddenCrawlers-0.frontend.rule: Host(`capili.lapanacea.es`);Path:/web,/web/{anything:.*},/website/info,/website/info/{anything:.*}
      traefik.main-0.frontend.rule: Host(`capili.lapanacea.es`)
      traefik.longpolling-0.frontend.rule: Host(`capili.lapanacea.es`);Path:/longpolling/{anything:.*}
      traefik.longpolling-0.port: 8072
      traefik.http.middlewares.capili-14-0-prod-buffering.buffering.retryExpression:
        IsNetworkError() && Attempts() < 5
      traefik.http.middlewares.capili-14-0-prod-compress.compress: "true"
      traefik.http.middlewares.capili-14-0-prod-forbid-crawlers.headers.customResponseHeaders.X-Robots-Tag:
        "noindex, nofollow"
      traefik.http.middlewares.capili-14-0-prod-addSTS.headers.forceSTSHeader: "true"
      traefik.http.middlewares.capili-14-0-prod-forceSecure.redirectScheme.scheme: https
      traefik.http.middlewares.capili-14-0-prod-forceSecure.redirectScheme.permanent: "true"
      traefik.http.services.capili-14-0-prod-main.loadbalancer.server.port: 8069
      traefik.http.services.capili-14-0-prod-longpolling.loadbalancer.server.port: 8072
      traefik.http.routers.capili-14-0-prod-main-0.rule: Host(`capili.lapanacea.es`)
      traefik.http.routers.capili-14-0-prod-main-0.service: capili-14-0-prod-main
      traefik.http.routers.capili-14-0-prod-main-0.middlewares:
        capili-14-0-prod-addSTS, capili-14-0-prod-buffering, capili-14-0-prod-compress,
        capili-14-0-prod-forceSecure
      traefik.http.routers.capili-14-0-prod-main-secure-0.rule: Host(`capili.lapanacea.es`)
      traefik.http.routers.capili-14-0-prod-main-secure-0.service: capili-14-0-prod-main
      traefik.http.routers.capili-14-0-prod-main-secure-0.middlewares:
        capili-14-0-prod-addSTS, capili-14-0-prod-buffering, capili-14-0-prod-compress,
        capili-14-0-prod-forceSecure
      traefik.http.routers.capili-14-0-prod-main-secure-0.tls: "true"
      traefik.http.routers.capili-14-0-prod-main-secure-0.tls.certResolver: letsencrypt
      traefik.http.routers.capili-14-0-prod-longpolling-0.rule:
        Host(`capili.lapanacea.es`) && PathPrefix(`/longpolling/`)
      traefik.http.routers.capili-14-0-prod-longpolling-0.service: capili-14-0-prod-longpolling
      traefik.http.routers.capili-14-0-prod-longpolling-0.middlewares:
        capili-14-0-prod-addSTS, capili-14-0-prod-forceSecure
      traefik.http.routers.capili-14-0-prod-longpolling-secure-0.rule:
        Host(`capili.lapanacea.es`) && PathPrefix(`/longpolling/`)
      traefik.http.routers.capili-14-0-prod-longpolling-secure-0.service: capili-14-0-prod-longpolling
      traefik.http.routers.capili-14-0-prod-longpolling-secure-0.middlewares:
        capili-14-0-prod-addSTS, capili-14-0-prod-forceSecure
      traefik.http.routers.capili-14-0-prod-longpolling-secure-0.tls: "true"
      traefik.http.routers.capili-14-0-prod-longpolling-secure-0.tls.certResolver: letsencrypt
      traefik.http.routers.capili-14-0-prod-forbiddenCrawlers-0.rule:
        Host(`capili.lapanacea.es`) && (PathPrefix(`/web/`, `/website/info/`) ||
        Path(`/web`, `/website/info`))
      traefik.http.routers.capili-14-0-prod-forbiddenCrawlers-0.service: capili-14-0-prod-main
      traefik.http.routers.capili-14-0-prod-forbiddenCrawlers-0.middlewares:
        capili-14-0-prod-addSTS, capili-14-0-prod-buffering, capili-14-0-prod-compress,
        capili-14-0-prod-forbid-crawlers, capili-14-0-prod-forceSecure
      traefik.http.routers.capili-14-0-prod-forbiddenCrawlers-secure-0.rule:
        Host(`capili.lapanacea.es`) && (PathPrefix(`/web/`, `/website/info/`) ||
        Path(`/web`, `/website/info`))
      traefik.http.routers.capili-14-0-prod-forbiddenCrawlers-secure-0.service: capili-14-0-prod-main
      traefik.http.routers.capili-14-0-prod-forbiddenCrawlers-secure-0.middlewares:
        capili-14-0-prod-addSTS, capili-14-0-prod-buffering, capili-14-0-prod-compress,
        capili-14-0-prod-forbid-crawlers, capili-14-0-prod-forceSecure
      traefik.http.routers.capili-14-0-prod-forbiddenCrawlers-secure-0.tls: "true"
      traefik.http.routers.capili-14-0-prod-forbiddenCrawlers-secure-0.tls.certResolver: letsencrypt

  db:
    extends:
      file: common.yaml
      service: db
    environment:
      DB_HOST: capili-14-0-prod-db
    env_file:
      - .docker/db-creation.env
    restart: unless-stopped
    networks:
      default:
        aliases:
          - "capili-14-0-prod-db"

networks:
  default:
    driver_opts:
      encrypted: 1

  inverseproxy_shared:
    external: true

volumes:
  filestore:
  db:
